#!/usr/bin/env bash
# Creates mac-cloud/.env from repo root .env + license-api service account.
# Usage: bash mac-cloud/scripts/setup-migration-env.sh
set -euo pipefail

MAC_CLOUD="$(cd "$(dirname "$0")/.." && pwd)"
ROOT="$(cd "$MAC_CLOUD/.." && pwd)"
ENV_OUT="$MAC_CLOUD/.env"
ROOT_ENV="$ROOT/.env"

REGISTRY_SA="${REGISTRY_SA_PATH:-$HOME/amlak-sale-product/license-api-server/service-account.json}"

if [[ ! -f "$ROOT_ENV" ]]; then
  echo "Missing $ROOT_ENV — copy mac-cloud/.env.example or project .env.example first."
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "$ROOT_ENV"
set +a

POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-}"
if [[ -z "$POSTGRES_PASSWORD" ]]; then
  echo "POSTGRES_PASSWORD not set in $ROOT_ENV"
  exit 1
fi

POSTGRES_USER="${POSTGRES_USER:-amlak}"
POSTGRES_DB="${POSTGRES_DB:-amlak}"
POSTGRES_HOST="${POSTGRES_HOST:-localhost}"
POSTGRES_PORT="${POSTGRES_PORT:-5432}"

# URL-encode password if it contains special chars (basic: warn only)
DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

FIREBASE_SA="${FIREBASE_SERVICE_ACCOUNT_JSON:-${AMLAK_ADMIN_FIREBASE_SERVICE_ACCOUNT_JSON:-}}"
if [[ -z "$FIREBASE_SA" ]]; then
  echo "WARN: FIREBASE_SERVICE_ACCOUNT_JSON / AMLAK_ADMIN_FIREBASE_SERVICE_ACCOUNT_JSON not in root .env"
  echo "      Add saudi-property-manager Admin SDK JSON before cutover."
fi

LICENSE_SA=""
if [[ -f "$REGISTRY_SA" ]]; then
  LICENSE_SA="$(cat "$REGISTRY_SA")"
  echo "Using registry SA: $REGISTRY_SA"
else
  echo "WARN: Registry SA not found at $REGISTRY_SA"
  echo "      Set LICENSE_REGISTRY_SERVICE_ACCOUNT_JSON manually for inventory."
fi

BUYER_MAP="${BUYER_FIREBASE_PROJECTS_JSON:-{}}"

{
  echo "# Generated by setup-migration-env.sh — DO NOT COMMIT"
  echo "DATABASE_URL=$DATABASE_URL"
  if [[ -n "$FIREBASE_SA" ]]; then
    echo "FIREBASE_SERVICE_ACCOUNT_JSON=$(echo "$FIREBASE_SA" | jq -c . 2>/dev/null || echo "$FIREBASE_SA")"
  fi
  if [[ -n "$LICENSE_SA" ]]; then
    echo "LICENSE_REGISTRY_SERVICE_ACCOUNT_JSON=$(echo "$LICENSE_SA" | jq -c . 2>/dev/null || echo "$LICENSE_SA")"
  fi
  echo "BUYER_FIREBASE_PROJECTS_JSON=$BUYER_MAP"
} > "$ENV_OUT"

chmod 600 "$ENV_OUT"
echo "Wrote $ENV_OUT"
echo "Next: cd mac-cloud && npm install && npm run migrate:inventory"
